Create notes app
AnaIoramashvili/NotesApplication pull request #1
Opened 2024-11-04 14:18 UTC by AnaIoramashvili

2024-11-04 14:37 UTC, GujMeister requested changes
Very readable code, please improve the areas listed below

2024-11-04 14:37 UTC, GujMeister commented on NotesApplication/Screens/Editor/NotesEditorViewController.swift
> +        if viewModel.isEditingMode {
Remove logic from viewDidLoad(). Make a separate function that is called in setupUI as the logic below is controlling how UI behaves.

2024-11-04 14:37 UTC, GujMeister commented on NotesApplication/Screens/Home/NotesViewController.swift
> +    private let viewModel = NotesViewModel()
Try to inject NotesViewModel into the NotesViewController

2024-11-04 14:37 UTC, GujMeister commented on NotesApplication/Data/DataComunication.swift
> +
Remove whitespace

2024-11-04 15:00 UTC, tamokakhidze requested changes
Font size

2024-11-04 15:00 UTC, tamokakhidze commented on NotesApplication/Alert/CustomAlert.swift
> +        label.font = .systemFont(ofSize: 17, weight: .medium)
Please make alert title bigger, 20 font size

2024-11-04 15:02 UTC, tamokakhidze approved these changes
Okay that's it

2024-11-04 15:23 UTC, GujMeister approved these changes
Thanks for addressing the issues

2024-11-04 15:23 UTC, merged

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Alert/CustomAlert.swift
> +        view.layer.cornerRadius = 12
You should have separate file or extension for constants. Please change that for whole file

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Alert/CustomAlert.swift
> +        label.text = "Are you sure you want to delete note?"
Same for string, create constants and use that value instead

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Alert/CustomAlert.swift
> +        backgroundColor = UIColor.black.withAlphaComponent(0.5)
In this function, you combine both adding subviews and applying constraints. it will be better if you will have separate function like setUpHierarchy() where you will have addSubview staff and separately will have setUpConstraints() function. Both this functions will be called inside setUp() function

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Alert/CustomAlert.swift
> +        buttonStackView.addArrangedSubview(deleteButton)
you can create extension like this to avoid writing same code twice:
   func addArrangedSubviews(_ subviews: UIView...) {
        subviews.forEach { subview in
            addArrangedSubview(subview)
        }
    } 
    
   and later use buttonStackView.addArrangedSubviews(cancelButton, deleteButton)

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Alert/CustomAlert.swift
> +            deleteButton.heightAnchor.constraint(equalToConstant: 40)
All values for sizing should be in constants.

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Alert/CustomAlert.swift
> +            infoImage.topAnchor.constraint(equalTo: containerView.topAnchor, constant: 20),
do you really need all these constraints?

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Cell/NoteTableViewCell.swift
> +        view.layer.cornerRadius = 8
sizing values should be in separate file or extension.

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Cell/NoteTableViewCell.swift
> +        label.numberOfLines = 0
instead of 0 you can use .zero which is better since you are avoiding number

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Alert/CustomAlert.swift
> +        buttonStackView.addArrangedSubview(deleteButton)
I prefer having this inside the stackView buttonStackView.addArrangedSubviews(cancelButton, deleteButton)
but it is up to you both works

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Alert/CustomAlert.swift
> +        button.translatesAutoresizingMaskIntoConstraints = false
if it is inside the stack view it does not need apply button.translatesAutoresizingMaskIntoConstraints = false. you will have it only for stackView

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Cell/NoteTableViewCell.swift
> +    private func setupUI() {
I have same comments as for CustomAlert file. Everything else is good for me

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Screens/Editor/NotesEditorViewController.swift
> +        }
Please have this separately, not inside this function. Also for setUpUI func, please consider my comment in previous files

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Screens/Editor/NotesEditorViewController.swift
> +
In my opinion it is better to have UIButton component seperately declared. Inside this function you should apply that button navbarbuttonitem and have the navigation staff only. func is called setupNavigationBar and you are creating UI component inside of it

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Screens/Editor/NotesEditorViewModel.swift
> +import Foundation
I think you do not need importing Foundation here

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Screens/Home/NotesViewModel.swift
> +    func numberOfNotes() -> Int {
insead of this you can have 
var numberOfNotes: Int {
        notes.count
    } and in tableview you can use as viewmodel. numberOfNotes but it is up to you

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Screens/Home/NotesViewController.swift
> +        cell.backgroundColor = .clear
If this never changes you should have these lines inside NoteTableViewCell

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Screens/Home/NotesViewController.swift
> +// MARK: - Note Editor Delegate
//MARK: - NotesEditorDelegate

mark title should be name of the delegate as you have this // MARK: - UITableViewDelegate

2024-11-05 08:13 UTC, AniDzamelashvili commented on NotesApplication/Screens/Home/NotesViewModel.swift
> +import Foundation
I think you can remove foundation importing